[book]
authors = ["Dustin Carlino"]
language = "en"
multilingual = false
src = "src"
title = "A/B Street"

[preprocessor.plantuml]

[output.html]

# TODO: Enable linkcheck. But first, deal with email addresses
# (https://github.com/Michael-F-Bryan/mdbook-linkcheck/issues/40) and the
# README.md -> index.md rewriting
#[output.linkcheck]
